name: FTP Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 103.191.209.67
          username: hazem@loarwater.com
          password: Hazem@39016h2
          port: 21
          protocol: ftp
          server-dir: public_html/loarwater.com/
          local-dir: ./
          exclude: |
            **/conn.php
            **/hmb/conn.php
            **/storage/**
            **/.git/**
